# Generated by Django 3.2.3 on 2022-02-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_alter_telegramaccount_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='reply_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='reply_5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
