# Generated by Django 3.2.3 on 2022-02-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_auto_20220202_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='reply_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='reply_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='reply_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='reply_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='reply_9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
