# Generated by Django 3.2.3 on 2022-01-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
