# Generated by Django 3.2.3 on 2022-01-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='services',
            field=models.ManyToManyField(related_name='accounts', to='services.Service', verbose_name='Услуги'),
        ),
    ]
