# Generated by Django 3.2.3 on 2022-01-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=5, max_digits=3, null=True),
        ),
    ]
