# Generated by Django 3.2.3 on 2022-01-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
    ]
