# Generated by Django 3.2.3 on 2022-01-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220106_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='rating',
            new_name='cutomer_rating',
        ),
        migrations.RemoveField(
            model_name='account',
            name='my_reviews_count',
        ),
        migrations.RemoveField(
            model_name='account',
            name='reviews_about_me_count',
        ),
        migrations.AddField(
            model_name='account',
            name='executor_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='my_reviews_about_customers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Мои отзывы о заказчиках'),
        ),
        migrations.AddField(
            model_name='account',
            name='my_reviews_about_executors_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Мои отзывы об исполнителях'),
        ),
        migrations.AddField(
            model_name='account',
            name='reviews_executors_about_me_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Отзывы заказчиков обо мне'),
        ),
    ]
