# Generated by Django 3.2.3 on 2022-01-07 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220106_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='cutomer_rating',
            new_name='customer_rating',
        ),
    ]
