# Generated by Django 3.2.3 on 2022-01-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_cutomer_rating_account_customer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='executor_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
