# Generated by Django 3.2.3 on 2022-06-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220126_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='my_services',
            field=models.JSONField(null=True),
        ),
    ]
