# Generated by Django 3.2.3 on 2022-06-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_my_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='my_services',
        ),
    ]
