# Generated by Django 3.2.3 on 2021-12-30 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(blank=True, max_length=150, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewables', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_reviewables.reviewable_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('reviewable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviewables.reviewable')),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Инстаграм',
                'verbose_name_plural': 'Инстаграм',
            },
            bases=('reviewables.reviewable',),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('reviewable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviewables.reviewable')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
            bases=('reviewables.reviewable',),
        ),
        migrations.CreateModel(
            name='VK',
            fields=[
                ('reviewable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviewables.reviewable')),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'ВК',
                'verbose_name_plural': 'ВК',
            },
            bases=('reviewables.reviewable',),
        ),
    ]
