# Generated by Django 3.2.3 on 2022-01-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviewables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewable',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='reviewable',
            unique_together={('screen_name', 'polymorphic_ctype')},
        ),
    ]
