# Generated by Django 3.2.3 on 2022-01-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewables', '0003_auto_20220106_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewable',
            name='customer_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='reviewable',
            name='executor_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
    ]
