# Generated by Django 3.2.3 on 2022-02-01 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewables', '0005_auto_20220126_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewable',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewables', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
