# Generated by Django 3.2.3 on 2021-12-31 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='content_type',
            new_name='resourcetype',
        ),
    ]
