# Generated by Django 3.2.3 on 2022-02-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_rename_content_type_check_resourcetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
