# Generated by Django 3.2.3 on 2022-01-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220105_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='count_likes',
        ),
        migrations.AddField(
            model_name='likeable',
            name='count_likes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
    ]
