# Generated by Django 3.2.3 on 2022-01-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220105_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributetitle',
            old_name='is_customer',
            new_name='about_customer',
        ),
    ]
