# Generated by Django 3.2.3 on 2022-01-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_rename_is_customer_attributetitle_about_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewtemplate',
            old_name='is_customer',
            new_name='about_customer',
        ),
    ]
