# Generated by Django 3.2.3 on 2022-01-17 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewables', '0004_auto_20220107_0230'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0006_alter_review_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttributeAvgValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_attributes_avg', to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reviews.attributetitle')),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewableAttributeAvgValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewables_attributes_avg', to='reviewables.reviewable')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reviews.attributetitle')),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
    ]
