# Generated by Django 3.2.3 on 2022-01-18 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0009_auto_20220118_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExecutorAttributeAvgValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_executor_attributes_avg', to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reviews.attributetitle')),
            ],
            options={
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='userexecuterattributeavgvalue',
            name='account',
        ),
        migrations.RemoveField(
            model_name='userexecuterattributeavgvalue',
            name='title',
        ),
        migrations.DeleteModel(
            name='AttributeTitleExecuter',
        ),
        migrations.DeleteModel(
            name='ReviewTemplateExecuter',
        ),
        migrations.CreateModel(
            name='AttributeTitleExecutor',
            fields=[
            ],
            options={
                'verbose_name': 'Название характеристики отзывов на Исполнителя',
                'verbose_name_plural': 'Названия характеристик отзывов на Исполнителя',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reviews.attributetitle',),
        ),
        migrations.CreateModel(
            name='ReviewTemplateExecutor',
            fields=[
            ],
            options={
                'verbose_name': 'Шаблон отзывов на Исполнителя',
                'verbose_name_plural': 'Шаблоны отзывов на Исполнителя',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reviews.reviewtemplate',),
        ),
        migrations.DeleteModel(
            name='UserExecuterAttributeAvgValue',
        ),
    ]
