# Generated by Django 3.2.3 on 2021-12-30 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Шаблон жалобы',
                'verbose_name_plural': 'Шаблоны жалоб',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(verbose_name='Текст')),
                ('review', models.PositiveIntegerField(null=True)),
                ('comment', models.PositiveIntegerField(null=True)),
                ('is_readed', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('resume', models.TextField(verbose_name='Что сделано')),
                ('accused', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_about_me', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ['-created_at', 'is_readed'],
            },
        ),
    ]
