# Generated by Django 3.2.3 on 2021-06-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at', 'is_readed'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='message',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
